<div class="container">
    <a href="<?php echo $this->serverUrl('/post/add'); ?>">Add Post</a>
    &nbsp;
    <h2>Post Details</h2>           
    <table class="datatable table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Content</th>
                <th>Created On</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($post)) {
                $i = 1;
                foreach ($post as $p) {
                    //   echo '<pre>';
                    print_r($p->created_on);
                    ?>
                    <tr>
                        <td><?php echo $i; ?></td>
                        <td><?php echo $p->title; ?></td>
                        <td><?php echo $p->content; ?></td>
                        <td><?php echo $p->created_on->date; //$date = date('Y-m-d h:i:s', strtotime($p->created_on->date));         ?></td>
                        <td><a href="<?php echo $this->serverUrl('/post/update/' . $p->id); ?>">Edit</a> | <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?php echo $this->serverUrl('/post/delete/' . $p->id); ?>">Delete</a></td>
                    </tr>
                    <?php
                    $i++;
                }
            }
            ?>

        </tbody>
    </table>
</div>

