<div class="container">
    <h2>Post Details</h2> 

    <div class="lhead">
        <a class="btn btn-primary pull-right" href="<?php echo $this->serverUrl('/post/add'); ?>">Add Post</a>
    </div>

    <table class="datatable table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Content</th>

                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($post)) {
                $i = 1;
                foreach ($post as $p) {
                    ?>
                    <tr>
                        <td><?php echo $i; ?></td>
                        <td><?php echo $p->title; ?></td>
                        <td><?php echo $p->content; ?></td> 
                        <td><a href="<?php echo $this->serverUrl('/post/update/' . $p->id); ?>">Edit</a> | <a onclick="return confirm('Are you sure you want to delete this post?');" href="<?php echo $this->serverUrl('/post/delete/' . $p->id); ?>">Delete</a></td>
                    </tr>
                    <?php
                    $i++;
                }
            }
            ?>

        </tbody>
    </table>
</div>

