<?php
$form = $this->forgotPasswordForm;
$form->setAttribute('action', $this->url('user', ['action' => 'forgotPassword']));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formElement($form->get('loginCsrf'));

$errorMessage = $this->flashMessenger()->getMessages();
?>

<h2 style="text-align: center;">Password Reset</h2>

<table align="center" cellpadding="5" >
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('email'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('email'));
            ?>
        </td>
    </tr>

    <tr>
        <td>&nbsp;</td>
        <td>
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
        </td>
    </tr>
</table>
<?php
echo $this->form()->closeTag();
?>