<?php
$form = $this->registerForm;

$form->setAttribute('action', $this->url('user', ['action' => 'register',]));

$form->prepare();

echo $this->form()->openTag($form);

$errorMessage = $this->errorList;
echo $this->formHidden($form->get('id'));
?>
<h2 class="center-b">Registration</h2>
<?php
if (isset($errorMessage) && count($errorMessage)) :
    ?>
    <div class="server-error padding-bottom_30 center-b">
        <ul>
            <?php
            if (isset($errorMessage)) {
                ?>
                <?php foreach ($errorMessage as $type => $msg) : ?>
                    <?php foreach ($msg as $error_type => $error_msg) : ?>
                        <li><span class="<?php echo $error_type; ?>"><?php echo $error_msg; ?></span></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php } ?>
        </ul>
    </div>
<?php endif; ?>

<table align="center" cellpadding="5" >
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('first_name'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('first_name'));
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('last_name'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('last_name'));
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('email'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('email'));
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('password'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('password'));
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('confirmpassword'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('confirmpassword'));
            ?>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
        </td>
    </tr>
</table>
<?php
echo $this->form()->closeTag();
?>
<p style="text-align: center;">
    Do you have a account? <a href="<?php echo $this->serverUrl('/user') ?>"> Login</a>
</p>