<?php
$form = $this->resetPasswordForm;

$form->setAttribute('action', $this->url('user', ['action' => 'resetPassword']));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formElement($form->get('loginCsrf'));

$errorMessage = $this->flashMessenger()->getMessages();
?>

<h2 style="text-align: center;">Password Reset</h2>

<?php
if (isset($errorMessage) && count($errorMessage)) :
    $errorMessage = $errorMessage[0];
    ?>
    <div class="server-error padding-bottom_30">
        <ul>
            <?php
            if (isset($errorMessage)) {
                ?>
                <?php foreach ($errorMessage as $type => $msg) : ?>
                    <?php foreach ($msg as $error_type => $error_msg) : ?>
                        <li><span class="<?php echo $error_type; ?>"><?php echo $error_msg; ?></span></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php } ?>
        </ul>
    </div>
<?php endif; ?>

<table align="center" cellpadding="5" >
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('password'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('password'));
            ?>
        </td>
    </tr>
    <tr>
        <td>
            <?php
            echo $this->formlabel($form->get('confirmpassword'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formelement($form->get('confirmpassword'));
            ?>
        </td>
    </tr>

    <tr>
        <td>&nbsp;</td>
        <td>
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
        </td>
    </tr>
</table>
<?php
echo $this->form()->closeTag();
?>