<?php

use Zend\Session\Container; // We need this when using sessions

$session = new Container('User');
?>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function () {
                $('.datatable').DataTable();
            });
        </script>

        <style>
            .lhead{
                padding-top: 10px;padding-bottom: 10px;
            }

        </style>
    </head>
    <body>
        <div class="container"> 

            <div class="lhead">
                <a  href="<?php
                if ($session->offsetGet('userId')) {
                    echo $this->serverUrl('/user/logout');
                } else {
                    echo $this->serverUrl('/user');
                }
                ?>" class="btn btn-info btn-lg pull-right">
                    <span class="glyphicon glyphicon-log-out"></span>  
                    <?php
                    if ($session->offsetGet('userId')) {
                        echo 'Logout';
                    } else {
                        echo 'Login';
                    }
                    ?>
                </a>
            </div>

        </div>

        <?php
        echo $this->content;
        ?>

    </body>
</html>