<div class="container-fluid text-center">    
    <div class="row content">
        <div class="col-sm-8 text-center"> 
            <a href="<?php echo $this->serverUrl('/admin/users') ?>" class="btn btn-primary">
                Users <span class="badge badge-light"><?php echo $this->usersCount; ?></span>
            </a>
            <a href="<?php echo $this->serverUrl('/admin/posts') ?>" class="btn btn-primary">
                Posts <span class="badge badge-light"> <?php echo $this->postsCount; ?></span>
            </a>
        </div>
    </div>
</div>
