<div class="container">    
    <div class="row">
        <div class="col-md-12">

            <h2>Users</h2>  
            <div>
                <a class="btn btn-primary pull-right" href="<?php echo $this->serverUrl('/admin/users/add'); ?>">Add User</a>
            </div>
            <table class="datatable table-condensed">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (!empty($this->users)) {
                        $i = 1;
                        foreach ($this->users as $key => $value) {
                            ?>
                            <tr>
                                <td><?php echo $i; ?></td>
                                <td><?php echo $value->first_name; ?></td>
                                <td><?php echo $value->last_name; ?></td>
                                <td><?php echo $value->email; ?></td>
                                <td><a href="<?php echo $this->serverUrl('/admin/users/update/' . $value->id); ?>">Edit</a> | <a onclick="return confirm('Are you sure you want to delete this user?');" href="<?php echo $this->serverUrl('/admin/users/delete/' . $value->id); ?>">Delete</a></td>
                            </tr>
                            <?php
                            $i++;
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
